version: '3.8'

services:
  back:
    image: spring4
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/Fulldb?createDatabaseIfNotExist=true
    depends_on:
      - mysqldb
    networks:
      - front-tier
      - back-tier


  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=system
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

    networks:
      - back-tier

  front:
    image: jen4
    ports:
      - 3000:3000
volumes:
  mysql:
  mysql_config:
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
